** quick intro to sgf files

so here is an sgf file.  it is a tree structure, so every semicolon
indicates a branch or "node".  this game doesn't have any branches so,
for now, just think of it like an array of nodes.

a game node has data in it marked by tags that say what kind of data
it is, and then in brackets some string.  the very first node has
information about the game, and then the first move is on the second
node.

this file is broken up with newlines, so you could use File.readlines
like i do in the current code. but sgf format doesn't require them, so
i would like to read in the whole file, remove all the newlines, and
divide up the resulting string at every semicolon.

#+begin_example
(;
EV[5th Kisei Title]
RO[1]
PB[Otake Hideo]
BR[9p]
PW[Fujisawa Shuko]
WR[9p]
TM[9h]
KM[5.5]
RE[W+R]
DT[1981-01-13,14]

;B[qd];W[dd];B[pp];W[dq];B[oc];W[co];B[jq];W[qi];B[qk];W[qf]
;B[fq];W[fo];B[hp];W[qq];B[pq];W[qp];B[qo];W[ro];B[rn];W[qn]
;B[po];W[rm];B[pn];W[sn];B[qm];W[ql];B[rn];W[pl];B[ol];W[rk]
;B[rp];W[qn];B[rq];W[pm];B[om];W[ho];B[go];W[gn];B[gp];W[fn]
;B[ci];W[cg];B[cl];W[ec];B[jc];W[hc];B[hn];W[hm];B[io];W[im]
;B[ei];W[dj];B[di];W[bk];B[ce];W[cd];B[bd];W[bc];B[de];W[bi]
;B[cj];W[bj];B[ck];W[dg];B[fd];W[ee];B[gl];W[ef];B[kn];W[fl]
;B[fk];W[gk];B[el];W[fm];B[fj];W[hk];B[cn];W[do];B[pf];W[qe]
;B[pd];W[je];B[id];W[gb];B[pe];W[dm];B[gi];W[if];B[ii];W[kb]
;B[kc];W[jb];B[lb];W[lc];B[ld];W[mc];B[mb];W[ic];B[kd];W[jd]
;B[ib];W[hb];B[md];W[er];B[jl];W[hs];B[hr];W[gs];B[ir];W[bm]
;B[cm];W[bn];B[bl];W[al];B[ik];W[jh];B[gg];W[gf];B[kf];W[ke]
;B[le];W[ig];B[li];W[nc];B[nd];W[oj];B[ok];W[qg];B[re];W[nj]
;B[mk];W[rf];B[rd];W[jm];B[km];W[pg];B[fg];W[ng];B[ff];W[fe]
;B[fr];W[fs];B[ih];W[jg];B[hf];W[ge];B[hg];W[he];B[pk];W[qr]
;B[rr];W[sp];B[eq];W[cr];B[dn];W[sr];B[pr];W[sq];B[qs];W[em]
;B[ep];W[eo];B[mj];W[nh];B[dl];W[jj])
#+end_example

the code i've written so far only pulls off the first node,
breaks it up by newlines, and then decodes the tags into symbols i can
pair up in a hash with the strings. i 'cheated' to get just what i 
wanted from the file at the time, which was the info in the first node.

start by developing a function or class that takes a file path and creates an
array of hashes that represent the data in the nodes.  use the tags
code i have in place already on the first node. for the rest of the game,
B indicates a black move and W is white. 
